ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:3857").setExtent([-311632.029421, 200205.512248, 2239429.565024, 1857464.504260]);
var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_RiskIndex_1 = new ol.format.GeoJSON();
var features_RiskIndex_1 = format_RiskIndex_1.readFeatures(json_RiskIndex_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RiskIndex_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_RiskIndex_1.addFeatures(features_RiskIndex_1);
var lyr_RiskIndex_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_RiskIndex_1, 
                style: style_RiskIndex_1,
                popuplayertitle: 'Risk Index',
                interactive: true,
    title: 'Risk Index<br />\
    <img src="styles/legend/RiskIndex_1_0.png" /> 0 - 29<br />\
    <img src="styles/legend/RiskIndex_1_1.png" /> 29 - 73<br />\
    <img src="styles/legend/RiskIndex_1_2.png" /> 73 - 85<br />\
    <img src="styles/legend/RiskIndex_1_3.png" /> 85 - 132<br />\
    <img src="styles/legend/RiskIndex_1_4.png" /> 132 - 2549<br />' });
var format_boundaries_2 = new ol.format.GeoJSON();
var features_boundaries_2 = format_boundaries_2.readFeatures(json_boundaries_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_boundaries_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_boundaries_2.addFeatures(features_boundaries_2);
var lyr_boundaries_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_boundaries_2, 
                style: style_boundaries_2,
                popuplayertitle: 'boundaries',
                interactive: true,
                title: '<img src="styles/legend/boundaries_2.png" /> boundaries'
            });
var format_army_3 = new ol.format.GeoJSON();
var features_army_3 = format_army_3.readFeatures(json_army_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_army_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_army_3.addFeatures(features_army_3);
var lyr_army_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_army_3, 
                style: style_army_3,
                popuplayertitle: 'army',
                interactive: true,
                title: '<img src="styles/legend/army_3.png" /> army'
            });
var format_police_4 = new ol.format.GeoJSON();
var features_police_4 = format_police_4.readFeatures(json_police_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_police_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_police_4.addFeatures(features_police_4);
var lyr_police_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_police_4, 
                style: style_police_4,
                popuplayertitle: 'police',
                interactive: true,
                title: '<img src="styles/legend/police_4.png" /> police'
            });
var format_checkpoints_5 = new ol.format.GeoJSON();
var features_checkpoints_5 = format_checkpoints_5.readFeatures(json_checkpoints_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_checkpoints_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_checkpoints_5.addFeatures(features_checkpoints_5);
var lyr_checkpoints_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_checkpoints_5, 
                style: style_checkpoints_5,
                popuplayertitle: 'checkpoints',
                interactive: true,
                title: '<img src="styles/legend/checkpoints_5.png" /> checkpoints'
            });

lyr_OpenStreetMap_0.setVisible(true);lyr_RiskIndex_1.setVisible(true);lyr_boundaries_2.setVisible(true);lyr_army_3.setVisible(true);lyr_police_4.setVisible(true);lyr_checkpoints_5.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_RiskIndex_1,lyr_boundaries_2,lyr_army_3,lyr_police_4,lyr_checkpoints_5];
lyr_RiskIndex_1.set('fieldAliases', {'fid': 'fid', 'name': 'name', 'type': 'type', 'code_hasc': 'code_hasc', 'provnum_ne': 'provnum_ne', 'gadm_level': 'gadm_level', 'postal': 'postal', 'area_sqkm': 'area_sqkm', 'sameascity': 'sameascity', 'labelrank': 'labelrank', 'name_len': 'name_len', 'mapcolor9': 'mapcolor9', 'mapcolor13': 'mapcolor13', 'fips': 'fips', 'fips_alt': 'fips_alt', 'woe_id': 'woe_id', 'woe_label': 'woe_label', 'woe_name': 'woe_name', 'latitude': 'latitude', 'longitude': 'longitude', 'sov_a3': 'sov_a3', 'adm0_a3': 'adm0_a3', 'adm0_label': 'adm0_label', 'admin': 'admin', 'geonunit': 'geonunit', 'gu_a3': 'gu_a3', 'gn_id': 'gn_id', 'gn_name': 'gn_name', 'gns_id': 'gns_id', 'gns_name': 'gns_name', 'gn_level': 'gn_level', 'gn_region': 'gn_region', 'gn_a1_code': 'gn_a1_code', 'region_sub': 'region_sub', 'sub_code': 'sub_code', 'gns_level': 'gns_level', 'gns_lang': 'gns_lang', 'gns_adm1': 'gns_adm1', 'gns_region': 'gns_region', 'min_label': 'min_label', 'max_label': 'max_label', 'min_zoom': 'min_zoom', 'wikidataid': 'wikidataid', 'ne_id': 'ne_id', 'debug_name_clean': 'debug_name_clean', 'crime_offence_name': 'crime_offence_name', 'crime_total': 'crime_total', 'checkpoint_risk_count': 'checkpoint_risk_count', 'checkpoint_risk_min': 'checkpoint_risk_min', 'checkpoint_risk_max': 'checkpoint_risk_max', 'checkpoint_risk_mean': 'checkpoint_risk_mean', 'police_risk_count': 'police_risk_count', 'police_risk_min': 'police_risk_min', 'police_risk_max': 'police_risk_max', 'police_risk_mean': 'police_risk_mean', 'checkpoint_risk_count_2': 'checkpoint_risk_count_2', 'checkpoint_risk_min_2': 'checkpoint_risk_min_2', 'checkpoint_risk_max_2': 'checkpoint_risk_max_2', 'checkpoint_risk_mean_2': 'checkpoint_risk_mean_2', 'landuse_norm_count': 'landuse_norm_count', 'landuse_norm_unique': 'landuse_norm_unique', 'landuse_norm_min': 'landuse_norm_min', 'landuse_norm_max': 'landuse_norm_max', 'landuse_norm_range': 'landuse_norm_range', 'landuse_norm_sum': 'landuse_norm_sum', 'landuse_norm_mean': 'landuse_norm_mean', 'landuse_norm_median': 'landuse_norm_median', 'landuse_norm_stddev': 'landuse_norm_stddev', 'landuse_norm_minority': 'landuse_norm_minority', 'landuse_norm_majority': 'landuse_norm_majority', 'landuse_norm_q1': 'landuse_norm_q1', 'landuse_norm_q3': 'landuse_norm_q3', 'landuse_norm_iqr': 'landuse_norm_iqr', 'road_norm_mean': 'road_norm_mean', 'army_risk_count': 'army_risk_count', 'army_risk_min': 'army_risk_min', 'army_risk_max': 'army_risk_max', 'army_risk_mean': 'army_risk_mean', 'crime_total_clean': 'crime_total_clean', 'final_risk_score': 'final_risk_score', 'spi': 'spi', 'spi_norm': 'spi_norm', 'spi_inverse': 'spi_inverse', 'final_risk_score_adj': 'final_risk_score_adj', 'threat_manual': 'threat_manual', 'final_risk_score_corrected': 'final_risk_score_corrected', 'threat_override': 'threat_override', 'adjusted_risk_score': 'adjusted_risk_score', });
lyr_boundaries_2.set('fieldAliases', {'fid': 'fid', 'name': 'name', 'type': 'type', 'code_hasc': 'code_hasc', 'provnum_ne': 'provnum_ne', 'gadm_level': 'gadm_level', 'postal': 'postal', 'area_sqkm': 'area_sqkm', 'sameascity': 'sameascity', 'labelrank': 'labelrank', 'name_len': 'name_len', 'mapcolor9': 'mapcolor9', 'mapcolor13': 'mapcolor13', 'fips': 'fips', 'fips_alt': 'fips_alt', 'woe_id': 'woe_id', 'woe_label': 'woe_label', 'woe_name': 'woe_name', 'latitude': 'latitude', 'longitude': 'longitude', 'sov_a3': 'sov_a3', 'adm0_a3': 'adm0_a3', 'adm0_label': 'adm0_label', 'admin': 'admin', 'geonunit': 'geonunit', 'gu_a3': 'gu_a3', 'gn_id': 'gn_id', 'gn_name': 'gn_name', 'gns_id': 'gns_id', 'gns_name': 'gns_name', 'gn_level': 'gn_level', 'gn_region': 'gn_region', 'gn_a1_code': 'gn_a1_code', 'region_sub': 'region_sub', 'sub_code': 'sub_code', 'gns_level': 'gns_level', 'gns_lang': 'gns_lang', 'gns_adm1': 'gns_adm1', 'gns_region': 'gns_region', 'min_label': 'min_label', 'max_label': 'max_label', 'min_zoom': 'min_zoom', 'wikidataid': 'wikidataid', 'ne_id': 'ne_id', 'Boundaries_wardname': 'Boundaries_wardname', 'Boundaries_lganame': 'Boundaries_lganame', 'Boundaries_statename': 'Boundaries_statename', });
lyr_army_3.set('fieldAliases', {'fid': 'fid', 'sn': 'sn', 'Name': 'Name', 'State': 'State', 'Military': 'Military', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'landuse': 'landuse', 'source:url': 'source:url', 'military_service': 'military_service', 'addr:street': 'addr:street', 'addr:city': 'addr:city', 'description': 'description', 'access': 'access', 'entrance': 'entrance', 'barrier': 'barrier', 'layer': 'layer', 'path': 'path', 'hub_id': 'hub_id', 'fid_2': 'fid_2', 'sn_2': 'sn_2', 'Name_2': 'Name_2', 'State_2': 'State_2', 'Military_2': 'Military_2', 'Latitude_2': 'Latitude_2', 'Longitude_2': 'Longitude_2', 'full_id_2': 'full_id_2', 'osm_id_2': 'osm_id_2', 'osm_type_2': 'osm_type_2', 'landuse_2': 'landuse_2', 'source:url_2': 'source:url_2', 'military_service_2': 'military_service_2', 'addr:street_2': 'addr:street_2', 'addr:city_2': 'addr:city_2', 'description_2': 'description_2', 'access_2': 'access_2', 'entrance_2': 'entrance_2', 'barrier_2': 'barrier_2', 'layer_2': 'layer_2', 'path_2': 'path_2', 'hub_id_2': 'hub_id_2', 'HubName': 'HubName', 'HubDist': 'HubDist', 'HubName_2': 'HubName_2', 'HubDist_2': 'HubDist_2', 'road_distance_m': 'road_distance_m', 'landuse_distance_m': 'landuse_distance_m', 'landuse_norm': 'landuse_norm', 'road_norm': 'road_norm', });
lyr_police_4.set('fieldAliases', {'fid': 'fid', 'globalid': 'globalid', 'uniq_id': 'uniq_id', 'timestamp': 'timestamp', 'editor': 'editor', 'scdy_edtor': 'scdy_edtor', 'wardname': 'wardname', 'wardcode': 'wardcode', 'lganame': 'lganame', 'lgacode': 'lgacode', 'statename': 'statename', 'statecode': 'statecode', 'source': 'source', 'plc_st_nam': 'plc_st_nam', 'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'amenity': 'amenity', 'internet_access:fee': 'internet_access:fee', 'internet_access': 'internet_access', 'branch': 'branch', 'source:position': 'source:position', 'operator:type': 'operator:type', 'source:date': 'source:date', 'survey:date': 'survey:date', 'visibility': 'visibility', 'tessellate': 'tessellate', 'extrude': 'extrude', 'entrance': 'entrance', 'place': 'place', 'office': 'office', 'phone': 'phone', 'ele': 'ele', 'email': 'email', 'addr:postcode': 'addr:postcode', 'opening_hours': 'opening_hours', 'project:pdevii': 'project:pdevii', 'wheelchair': 'wheelchair', 'check_date': 'check_date', 'addr:housenumber': 'addr:housenumber', 'name:en': 'name:en', 'name:ar': 'name:ar', 'barrier': 'barrier', 'project:mappingforniger': 'project:mappingforniger', 'alt_name': 'alt_name', 'addr:street': 'addr:street', 'addr:city': 'addr:city', 'designation': 'designation', 'name:fr': 'name:fr', 'description': 'description', 'access': 'access', 'shop': 'shop', 'operator': 'operator', 'name': 'name', 'historic': 'historic', 'layer': 'layer', 'path': 'path', });
lyr_checkpoints_5.set('fieldAliases', {'fid': 'fid', 'fid_2': 'fid_2', 'HubName': 'HubName', 'HubDist': 'HubDist', 'hub_id': 'hub_id', 'landuse_distance_m': 'landuse_distance_m', 'HubName_2': 'HubName_2', 'HubDist_2': 'HubDist_2', 'road_distance_m': 'road_distance_m', 'landuse_norm': 'landuse_norm', 'road_norm': 'road_norm', 'checkpoint_risk': 'checkpoint_risk', });
lyr_RiskIndex_1.set('fieldImages', {'fid': 'TextEdit', 'name': 'TextEdit', 'type': 'TextEdit', 'code_hasc': 'TextEdit', 'provnum_ne': 'Range', 'gadm_level': 'Range', 'postal': 'TextEdit', 'area_sqkm': 'Range', 'sameascity': 'Range', 'labelrank': 'Range', 'name_len': 'Range', 'mapcolor9': 'Range', 'mapcolor13': 'Range', 'fips': 'TextEdit', 'fips_alt': 'TextEdit', 'woe_id': 'Range', 'woe_label': 'TextEdit', 'woe_name': 'TextEdit', 'latitude': 'TextEdit', 'longitude': 'TextEdit', 'sov_a3': 'TextEdit', 'adm0_a3': 'TextEdit', 'adm0_label': 'Range', 'admin': 'TextEdit', 'geonunit': 'TextEdit', 'gu_a3': 'TextEdit', 'gn_id': 'Range', 'gn_name': 'TextEdit', 'gns_id': 'Range', 'gns_name': 'TextEdit', 'gn_level': 'Range', 'gn_region': 'TextEdit', 'gn_a1_code': 'TextEdit', 'region_sub': 'TextEdit', 'sub_code': 'TextEdit', 'gns_level': 'Range', 'gns_lang': 'TextEdit', 'gns_adm1': 'TextEdit', 'gns_region': 'TextEdit', 'min_label': 'TextEdit', 'max_label': 'TextEdit', 'min_zoom': 'TextEdit', 'wikidataid': 'TextEdit', 'ne_id': 'TextEdit', 'debug_name_clean': 'TextEdit', 'crime_offence_name': 'TextEdit', 'crime_total': 'TextEdit', 'checkpoint_risk_count': 'TextEdit', 'checkpoint_risk_min': 'TextEdit', 'checkpoint_risk_max': 'TextEdit', 'checkpoint_risk_mean': 'TextEdit', 'police_risk_count': 'TextEdit', 'police_risk_min': 'TextEdit', 'police_risk_max': 'TextEdit', 'police_risk_mean': 'TextEdit', 'checkpoint_risk_count_2': 'TextEdit', 'checkpoint_risk_min_2': 'TextEdit', 'checkpoint_risk_max_2': 'TextEdit', 'checkpoint_risk_mean_2': 'TextEdit', 'landuse_norm_count': 'TextEdit', 'landuse_norm_unique': 'TextEdit', 'landuse_norm_min': 'TextEdit', 'landuse_norm_max': 'TextEdit', 'landuse_norm_range': 'TextEdit', 'landuse_norm_sum': 'TextEdit', 'landuse_norm_mean': 'TextEdit', 'landuse_norm_median': 'TextEdit', 'landuse_norm_stddev': 'TextEdit', 'landuse_norm_minority': 'TextEdit', 'landuse_norm_majority': 'TextEdit', 'landuse_norm_q1': 'TextEdit', 'landuse_norm_q3': 'TextEdit', 'landuse_norm_iqr': 'TextEdit', 'road_norm_mean': 'TextEdit', 'army_risk_count': 'TextEdit', 'army_risk_min': 'TextEdit', 'army_risk_max': 'TextEdit', 'army_risk_mean': 'TextEdit', 'crime_total_clean': 'TextEdit', 'final_risk_score': 'Range', 'spi': 'TextEdit', 'spi_norm': 'TextEdit', 'spi_inverse': 'TextEdit', 'final_risk_score_adj': 'TextEdit', 'threat_manual': 'TextEdit', 'final_risk_score_corrected': 'TextEdit', 'threat_override': 'TextEdit', 'adjusted_risk_score': 'TextEdit', });
lyr_boundaries_2.set('fieldImages', {'fid': 'TextEdit', 'name': 'TextEdit', 'type': 'TextEdit', 'code_hasc': 'TextEdit', 'provnum_ne': 'Range', 'gadm_level': 'Range', 'postal': 'TextEdit', 'area_sqkm': 'Range', 'sameascity': 'Range', 'labelrank': 'Range', 'name_len': 'Range', 'mapcolor9': 'Range', 'mapcolor13': 'Range', 'fips': 'TextEdit', 'fips_alt': 'TextEdit', 'woe_id': 'Range', 'woe_label': 'TextEdit', 'woe_name': 'TextEdit', 'latitude': 'TextEdit', 'longitude': 'TextEdit', 'sov_a3': 'TextEdit', 'adm0_a3': 'TextEdit', 'adm0_label': 'Range', 'admin': 'TextEdit', 'geonunit': 'TextEdit', 'gu_a3': 'TextEdit', 'gn_id': 'Range', 'gn_name': 'TextEdit', 'gns_id': 'Range', 'gns_name': 'TextEdit', 'gn_level': 'Range', 'gn_region': 'TextEdit', 'gn_a1_code': 'TextEdit', 'region_sub': 'TextEdit', 'sub_code': 'TextEdit', 'gns_level': 'Range', 'gns_lang': 'TextEdit', 'gns_adm1': 'TextEdit', 'gns_region': 'TextEdit', 'min_label': 'TextEdit', 'max_label': 'TextEdit', 'min_zoom': 'TextEdit', 'wikidataid': 'TextEdit', 'ne_id': 'TextEdit', 'Boundaries_wardname': 'TextEdit', 'Boundaries_lganame': 'TextEdit', 'Boundaries_statename': 'TextEdit', });
lyr_army_3.set('fieldImages', {'fid': 'TextEdit', 'sn': 'Range', 'Name': 'TextEdit', 'State': 'TextEdit', 'Military': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'landuse': 'TextEdit', 'source:url': 'TextEdit', 'military_service': 'TextEdit', 'addr:street': 'TextEdit', 'addr:city': 'TextEdit', 'description': 'TextEdit', 'access': 'TextEdit', 'entrance': 'TextEdit', 'barrier': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', 'hub_id': 'Range', 'fid_2': 'TextEdit', 'sn_2': 'Range', 'Name_2': 'TextEdit', 'State_2': 'TextEdit', 'Military_2': 'TextEdit', 'Latitude_2': 'TextEdit', 'Longitude_2': 'TextEdit', 'full_id_2': 'TextEdit', 'osm_id_2': 'TextEdit', 'osm_type_2': 'TextEdit', 'landuse_2': 'TextEdit', 'source:url_2': 'TextEdit', 'military_service_2': 'TextEdit', 'addr:street_2': 'TextEdit', 'addr:city_2': 'TextEdit', 'description_2': 'TextEdit', 'access_2': 'TextEdit', 'entrance_2': 'TextEdit', 'barrier_2': 'TextEdit', 'layer_2': 'TextEdit', 'path_2': 'TextEdit', 'hub_id_2': 'Range', 'HubName': 'TextEdit', 'HubDist': 'TextEdit', 'HubName_2': 'TextEdit', 'HubDist_2': 'TextEdit', 'road_distance_m': 'Range', 'landuse_distance_m': 'TextEdit', 'landuse_norm': 'TextEdit', 'road_norm': 'TextEdit', });
lyr_police_4.set('fieldImages', {'fid': 'TextEdit', 'globalid': 'TextEdit', 'uniq_id': 'TextEdit', 'timestamp': 'DateTime', 'editor': 'TextEdit', 'scdy_edtor': 'TextEdit', 'wardname': 'TextEdit', 'wardcode': 'TextEdit', 'lganame': 'TextEdit', 'lgacode': 'TextEdit', 'statename': 'TextEdit', 'statecode': 'TextEdit', 'source': 'TextEdit', 'plc_st_nam': 'TextEdit', 'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'amenity': 'TextEdit', 'internet_access:fee': 'TextEdit', 'internet_access': 'TextEdit', 'branch': 'TextEdit', 'source:position': 'TextEdit', 'operator:type': 'TextEdit', 'source:date': 'TextEdit', 'survey:date': 'TextEdit', 'visibility': 'TextEdit', 'tessellate': 'TextEdit', 'extrude': 'TextEdit', 'entrance': 'TextEdit', 'place': 'TextEdit', 'office': 'TextEdit', 'phone': 'TextEdit', 'ele': 'TextEdit', 'email': 'TextEdit', 'addr:postcode': 'TextEdit', 'opening_hours': 'TextEdit', 'project:pdevii': 'TextEdit', 'wheelchair': 'TextEdit', 'check_date': 'TextEdit', 'addr:housenumber': 'TextEdit', 'name:en': 'TextEdit', 'name:ar': 'TextEdit', 'barrier': 'TextEdit', 'project:mappingforniger': 'TextEdit', 'alt_name': 'TextEdit', 'addr:street': 'TextEdit', 'addr:city': 'TextEdit', 'designation': 'TextEdit', 'name:fr': 'TextEdit', 'description': 'TextEdit', 'access': 'TextEdit', 'shop': 'TextEdit', 'operator': 'TextEdit', 'name': 'TextEdit', 'historic': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', });
lyr_checkpoints_5.set('fieldImages', {'fid': 'TextEdit', 'fid_2': 'TextEdit', 'HubName': 'TextEdit', 'HubDist': 'TextEdit', 'hub_id': 'Range', 'landuse_distance_m': 'Range', 'HubName_2': 'TextEdit', 'HubDist_2': 'TextEdit', 'road_distance_m': 'TextEdit', 'landuse_norm': 'TextEdit', 'road_norm': 'TextEdit', 'checkpoint_risk': 'TextEdit', });
lyr_RiskIndex_1.set('fieldLabels', {'fid': 'no label', 'name': 'inline label - visible with data', 'type': 'no label', 'code_hasc': 'no label', 'provnum_ne': 'no label', 'gadm_level': 'no label', 'postal': 'no label', 'area_sqkm': 'no label', 'sameascity': 'no label', 'labelrank': 'no label', 'name_len': 'no label', 'mapcolor9': 'no label', 'mapcolor13': 'no label', 'fips': 'no label', 'fips_alt': 'no label', 'woe_id': 'no label', 'woe_label': 'no label', 'woe_name': 'no label', 'latitude': 'no label', 'longitude': 'no label', 'sov_a3': 'no label', 'adm0_a3': 'no label', 'adm0_label': 'no label', 'admin': 'no label', 'geonunit': 'no label', 'gu_a3': 'no label', 'gn_id': 'no label', 'gn_name': 'no label', 'gns_id': 'no label', 'gns_name': 'no label', 'gn_level': 'no label', 'gn_region': 'no label', 'gn_a1_code': 'no label', 'region_sub': 'no label', 'sub_code': 'no label', 'gns_level': 'no label', 'gns_lang': 'no label', 'gns_adm1': 'no label', 'gns_region': 'no label', 'min_label': 'no label', 'max_label': 'no label', 'min_zoom': 'no label', 'wikidataid': 'no label', 'ne_id': 'no label', 'debug_name_clean': 'no label', 'crime_offence_name': 'no label', 'crime_total': 'no label', 'checkpoint_risk_count': 'no label', 'checkpoint_risk_min': 'no label', 'checkpoint_risk_max': 'no label', 'checkpoint_risk_mean': 'no label', 'police_risk_count': 'no label', 'police_risk_min': 'no label', 'police_risk_max': 'no label', 'police_risk_mean': 'no label', 'checkpoint_risk_count_2': 'no label', 'checkpoint_risk_min_2': 'no label', 'checkpoint_risk_max_2': 'no label', 'checkpoint_risk_mean_2': 'no label', 'landuse_norm_count': 'no label', 'landuse_norm_unique': 'no label', 'landuse_norm_min': 'no label', 'landuse_norm_max': 'no label', 'landuse_norm_range': 'no label', 'landuse_norm_sum': 'no label', 'landuse_norm_mean': 'no label', 'landuse_norm_median': 'no label', 'landuse_norm_stddev': 'no label', 'landuse_norm_minority': 'no label', 'landuse_norm_majority': 'no label', 'landuse_norm_q1': 'no label', 'landuse_norm_q3': 'no label', 'landuse_norm_iqr': 'no label', 'road_norm_mean': 'no label', 'army_risk_count': 'no label', 'army_risk_min': 'no label', 'army_risk_max': 'no label', 'army_risk_mean': 'no label', 'crime_total_clean': 'no label', 'final_risk_score': 'no label', 'spi': 'no label', 'spi_norm': 'no label', 'spi_inverse': 'no label', 'final_risk_score_adj': 'no label', 'threat_manual': 'no label', 'final_risk_score_corrected': 'no label', 'threat_override': 'no label', 'adjusted_risk_score': 'inline label - visible with data', });
lyr_boundaries_2.set('fieldLabels', {'fid': 'no label', 'name': 'no label', 'type': 'no label', 'code_hasc': 'no label', 'provnum_ne': 'no label', 'gadm_level': 'no label', 'postal': 'no label', 'area_sqkm': 'no label', 'sameascity': 'no label', 'labelrank': 'no label', 'name_len': 'no label', 'mapcolor9': 'no label', 'mapcolor13': 'no label', 'fips': 'no label', 'fips_alt': 'no label', 'woe_id': 'no label', 'woe_label': 'no label', 'woe_name': 'no label', 'latitude': 'no label', 'longitude': 'no label', 'sov_a3': 'no label', 'adm0_a3': 'no label', 'adm0_label': 'no label', 'admin': 'no label', 'geonunit': 'no label', 'gu_a3': 'no label', 'gn_id': 'no label', 'gn_name': 'no label', 'gns_id': 'no label', 'gns_name': 'no label', 'gn_level': 'no label', 'gn_region': 'no label', 'gn_a1_code': 'no label', 'region_sub': 'no label', 'sub_code': 'no label', 'gns_level': 'no label', 'gns_lang': 'no label', 'gns_adm1': 'no label', 'gns_region': 'no label', 'min_label': 'no label', 'max_label': 'no label', 'min_zoom': 'no label', 'wikidataid': 'no label', 'ne_id': 'no label', 'Boundaries_wardname': 'no label', 'Boundaries_lganame': 'no label', 'Boundaries_statename': 'no label', });
lyr_army_3.set('fieldLabels', {'fid': 'no label', 'sn': 'no label', 'Name': 'no label', 'State': 'no label', 'Military': 'no label', 'Latitude': 'no label', 'Longitude': 'no label', 'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'landuse': 'no label', 'source:url': 'no label', 'military_service': 'no label', 'addr:street': 'no label', 'addr:city': 'no label', 'description': 'no label', 'access': 'no label', 'entrance': 'no label', 'barrier': 'no label', 'layer': 'no label', 'path': 'no label', 'hub_id': 'no label', 'fid_2': 'no label', 'sn_2': 'no label', 'Name_2': 'no label', 'State_2': 'no label', 'Military_2': 'no label', 'Latitude_2': 'no label', 'Longitude_2': 'no label', 'full_id_2': 'no label', 'osm_id_2': 'no label', 'osm_type_2': 'no label', 'landuse_2': 'no label', 'source:url_2': 'no label', 'military_service_2': 'no label', 'addr:street_2': 'no label', 'addr:city_2': 'no label', 'description_2': 'no label', 'access_2': 'no label', 'entrance_2': 'no label', 'barrier_2': 'no label', 'layer_2': 'no label', 'path_2': 'no label', 'hub_id_2': 'no label', 'HubName': 'no label', 'HubDist': 'no label', 'HubName_2': 'no label', 'HubDist_2': 'no label', 'road_distance_m': 'no label', 'landuse_distance_m': 'no label', 'landuse_norm': 'no label', 'road_norm': 'no label', });
lyr_police_4.set('fieldLabels', {'fid': 'no label', 'globalid': 'no label', 'uniq_id': 'no label', 'timestamp': 'no label', 'editor': 'no label', 'scdy_edtor': 'no label', 'wardname': 'no label', 'wardcode': 'no label', 'lganame': 'no label', 'lgacode': 'no label', 'statename': 'no label', 'statecode': 'no label', 'source': 'no label', 'plc_st_nam': 'no label', 'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'amenity': 'no label', 'internet_access:fee': 'no label', 'internet_access': 'no label', 'branch': 'no label', 'source:position': 'no label', 'operator:type': 'no label', 'source:date': 'no label', 'survey:date': 'no label', 'visibility': 'no label', 'tessellate': 'no label', 'extrude': 'no label', 'entrance': 'no label', 'place': 'no label', 'office': 'no label', 'phone': 'no label', 'ele': 'no label', 'email': 'no label', 'addr:postcode': 'no label', 'opening_hours': 'no label', 'project:pdevii': 'no label', 'wheelchair': 'no label', 'check_date': 'no label', 'addr:housenumber': 'no label', 'name:en': 'no label', 'name:ar': 'no label', 'barrier': 'no label', 'project:mappingforniger': 'no label', 'alt_name': 'no label', 'addr:street': 'no label', 'addr:city': 'no label', 'designation': 'no label', 'name:fr': 'no label', 'description': 'no label', 'access': 'no label', 'shop': 'no label', 'operator': 'no label', 'name': 'no label', 'historic': 'no label', 'layer': 'no label', 'path': 'no label', });
lyr_checkpoints_5.set('fieldLabels', {'fid': 'no label', 'fid_2': 'no label', 'HubName': 'no label', 'HubDist': 'no label', 'hub_id': 'no label', 'landuse_distance_m': 'no label', 'HubName_2': 'no label', 'HubDist_2': 'no label', 'road_distance_m': 'no label', 'landuse_norm': 'no label', 'road_norm': 'no label', 'checkpoint_risk': 'no label', });
lyr_checkpoints_5.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});